In [1]:
print('''Let's start the pytorch journey!''' )

Let's start the pytorch journey!


In [4]:
!nvidia-smi

Sun Jun 16 01:03:21 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.99                 Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090      WDDM  |   00000000:01:00.0  On |                  Off |
|  0%   44C    P5             48W /  450W |    1578MiB /  24564MiB |     24%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [6]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
torch.cuda.is_available()

True

In [8]:
print(torch.__version__)

2.3.1+cu121


In [9]:
##Intro to tensors

In [11]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [12]:
scalar.ndim

0

In [14]:
#Get tensor back as python int
scalar.item()

7

In [19]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [20]:
vector.ndim

1

In [21]:
vector.shape

torch.Size([2])

In [30]:
matrix = torch.tensor([[7,7,5],
                       [4,5,6]])
matrix

tensor([[7, 7, 5],
        [4, 5, 6]])

In [31]:
matrix.ndim

2

In [32]:
matrix[1]

tensor([4, 5, 6])

In [35]:
matrix.shape
#row by column size([row_no,column_no])

torch.Size([2, 3])

In [36]:
tensor = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [6,7,8]]])
tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [37]:
tensor.ndim

3

In [38]:
tensor.shape

torch.Size([1, 3, 3])

In [46]:
tensor[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [67]:
#Random Tensor of size (4,5,4)
random_tensor = torch.rand(4,5,4)

In [68]:
random_tensor

tensor([[[0.5966, 0.4067, 0.8082, 0.4168],
         [0.9306, 0.5818, 0.5193, 0.5506],
         [0.9653, 0.9986, 0.9998, 0.2014],
         [0.5687, 0.8234, 0.2617, 0.9338],
         [0.8187, 0.2084, 0.4569, 0.1143]],

        [[0.2319, 0.1271, 0.6291, 0.3752],
         [0.3181, 0.2576, 0.5624, 0.8853],
         [0.2883, 0.9971, 0.6582, 0.4430],
         [0.6448, 0.1628, 0.7916, 0.6591],
         [0.5548, 0.5301, 0.1286, 0.5734]],

        [[0.0146, 0.1516, 0.3779, 0.5945],
         [0.5793, 0.0302, 0.4488, 0.3869],
         [0.6910, 0.7980, 0.2984, 0.8441],
         [0.7623, 0.6668, 0.2144, 0.6007],
         [0.6161, 0.7011, 0.5230, 0.2435]],

        [[0.9855, 0.4953, 0.4351, 0.4899],
         [0.1882, 0.4526, 0.9771, 0.0654],
         [0.2196, 0.8428, 0.3974, 0.3827],
         [0.6460, 0.3571, 0.8134, 0.6571],
         [0.2510, 0.4010, 0.7467, 0.3678]]])

In [61]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [69]:
random_image_size_tensor

tensor([[[0.3990, 0.2382, 0.1381],
         [0.0085, 0.2285, 0.9973],
         [0.1170, 0.9843, 0.9861],
         ...,
         [0.5877, 0.1887, 0.3301],
         [0.8772, 0.2888, 0.3118],
         [0.4109, 0.2086, 0.1841]],

        [[0.0047, 0.4508, 0.6390],
         [0.0551, 0.0668, 0.1677],
         [0.3856, 0.1467, 0.2912],
         ...,
         [0.3290, 0.7570, 0.1465],
         [0.0176, 0.0927, 0.7571],
         [0.1392, 0.9386, 0.3578]],

        [[0.4223, 0.6743, 0.3687],
         [0.5009, 0.5937, 0.6488],
         [0.0430, 0.6757, 0.9449],
         ...,
         [0.5368, 0.8668, 0.7468],
         [0.5271, 0.4431, 0.4866],
         [0.2701, 0.8315, 0.5309]],

        ...,

        [[0.8021, 0.5016, 0.6070],
         [0.6437, 0.3253, 0.7374],
         [0.5832, 0.3275, 0.0179],
         ...,
         [0.3228, 0.2058, 0.8902],
         [0.1400, 0.7367, 0.4912],
         [0.9300, 0.7353, 0.0049]],

        [[0.3517, 0.9228, 0.4872],
         [0.4297, 0.3242, 0.5481],
         [0.

In [76]:
#zeros and ones
zeros = tensor.new_zeros(3,4)
zeros

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [ ]:
ones = tensor.new_ones(3,4)
ones