In [6]:
print('''Let's start the pytorch journey!''' )

Let's start the pytorch journey!


In [7]:
!nvidia-smi

Sun Jun 16 15:54:58 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.99                 Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090      WDDM  |   00000000:01:00.0  On |                  Off |
|  0%   45C    P5             51W /  450W |    1357MiB /  24564MiB |     22%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [8]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [9]:
torch.cuda.is_available()

True

In [10]:
print(torch.__version__)

2.3.1+cu121


In [11]:
##Intro to tensors

In [12]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [13]:
scalar.ndim

0

In [14]:
#Get tensor back as python int
scalar.item()

7

In [15]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [16]:
vector.ndim

1

In [17]:
vector.shape

torch.Size([2])

In [18]:
matrix = torch.tensor([[7,7,5],
                       [4,5,6]])
matrix

tensor([[7, 7, 5],
        [4, 5, 6]])

In [19]:
matrix.ndim

2

In [20]:
matrix[1]

tensor([4, 5, 6])

In [21]:
matrix.shape
#row by column size([row_no,column_no])

torch.Size([2, 3])

In [22]:
tensor = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [6,7,8]]])
tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [23]:
tensor.ndim

3

In [24]:
tensor.shape

torch.Size([1, 3, 3])

In [25]:
tensor[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [26]:
#Random Tensor of size (4,5,4)
random_tensor = torch.rand(4,5,4)

In [27]:
random_tensor

tensor([[[0.6889, 0.2903, 0.5437, 0.0226],
         [0.0489, 0.1043, 0.5363, 0.7689],
         [0.1256, 0.0938, 0.6177, 0.7257],
         [0.7572, 0.0050, 0.4571, 0.5999],
         [0.5797, 0.6598, 0.6729, 0.2855]],

        [[0.7107, 0.2087, 0.3051, 0.3580],
         [0.4031, 0.9674, 0.8478, 0.8526],
         [0.4788, 0.8713, 0.0185, 0.2532],
         [0.2151, 0.6073, 0.8487, 0.1971],
         [0.4979, 0.2479, 0.1656, 0.6028]],

        [[0.8880, 0.6492, 0.7331, 0.6080],
         [0.6192, 0.5642, 0.3087, 0.2151],
         [0.0465, 0.2473, 0.2696, 0.5181],
         [0.3792, 0.3797, 0.2877, 0.0948],
         [0.0470, 0.3758, 0.6605, 0.1693]],

        [[0.5249, 0.3527, 0.1805, 0.8352],
         [0.7793, 0.0642, 0.6766, 0.8907],
         [0.9742, 0.3815, 0.3909, 0.2848],
         [0.7004, 0.2451, 0.2735, 0.8658],
         [0.3631, 0.0563, 0.4593, 0.2183]]])

In [28]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [29]:
random_image_size_tensor

tensor([[[0.1376, 0.6327, 0.4610],
         [0.1778, 0.1468, 0.0075],
         [0.6250, 0.7869, 0.5300],
         ...,
         [0.6431, 0.4793, 0.0868],
         [0.0946, 0.1737, 0.4648],
         [0.8017, 0.5518, 0.6986]],

        [[0.4456, 0.5407, 0.1721],
         [0.4735, 0.2644, 0.8919],
         [0.8094, 0.5730, 0.9263],
         ...,
         [0.8083, 0.6331, 0.3184],
         [0.1199, 0.1332, 0.1942],
         [0.4354, 0.2562, 0.4919]],

        [[0.1002, 0.3343, 0.5280],
         [0.1941, 0.4631, 0.5716],
         [0.1811, 0.9076, 0.4250],
         ...,
         [0.0920, 0.4548, 0.5190],
         [0.2725, 0.8105, 0.0264],
         [0.2757, 0.7098, 0.1606]],

        ...,

        [[0.2826, 0.5343, 0.2062],
         [0.9561, 0.3183, 0.3344],
         [0.9418, 0.0627, 0.5257],
         ...,
         [0.3135, 0.4119, 0.3490],
         [0.6616, 0.3641, 0.3429],
         [0.7692, 0.2077, 0.2694]],

        [[0.8502, 0.8447, 0.5395],
         [0.1746, 0.1211, 0.0541],
         [0.

In [30]:
#zeros and ones
zeros = tensor.new_zeros(3,4)
zeros

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [31]:
ones = tensor.new_ones(3,4)
ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [32]:
one_to_ten = torch.range(1,10)

C:\Users\User\AppData\Local\Temp\ipykernel_21136\452320836.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = torch.range(1,10)


In [33]:
#tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device='cuda',
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [35]:
#Tensor multiply
#Tensor addition
#Tensor subtraction
#Tensor max
#Tensor min
#Matrix multiplication (dot)

In [36]:
#Argmax - finds the index of maximum number in the tensors

In [37]:
#Reshaping, stacking, squeezing and unsqueezing

#Reshaping - reshapes an input tensor to a defined shape
#View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
#Stacking - Combine multiple tensors on the top of each other (vstack) or side by siide(hstack)
# Squeeze - Removes all '1' dimension from a tensor
# Unsqeeze - Add a '1' dimension to a target tensor
# Permute - Return aview of the input with dimensions permuted (swapped) in a certain way

In [38]:
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [41]:
x_reshaped = x.reshape(9,1)

In [43]:
x_reshaped, x_reshaped.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [44]:
z = x.view(9,1)
z, z.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [47]:
#Stack
s_stacked = torch.stack([x,x,x], dim=0)
s_stacked, s_stacked.shape

(tensor([[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3],
         [4, 4, 4],
         [5, 5, 5],
         [6, 6, 6],
         [7, 7, 7],
         [8, 8, 8],
         [9, 9, 9]]),
 torch.Size([9, 3]))