## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`Start with random numbers -> tensor operations -> update raandom numbers to try and make them of the data -> again -> again -> again`

To reduce the randomness in neural networks and Pytorch we use 'random seed'


In [1]:
import torch

In [4]:
torch.rand(2,3,3)

tensor([[[0.4097, 0.8807, 0.8491],
         [0.5336, 0.7642, 0.3411],
         [0.9989, 0.1780, 0.7820]],

        [[0.4922, 0.5958, 0.8730],
         [0.9059, 0.5912, 0.1184],
         [0.1076, 0.9214, 0.1259]]])

In [5]:
#Create two random tensors
randA = torch.rand(3,4)
randB = torch.rand(3,4)

print(randA)
print(randB)
print(randA == randB)

tensor([[0.4716, 0.8967, 0.4249, 0.9361],
        [0.0559, 0.8862, 0.9013, 0.8551],
        [0.3368, 0.3578, 0.1925, 0.2222]])
tensor([[0.7593, 0.7111, 0.9896, 0.5811],
        [0.6098, 0.2984, 0.6506, 0.6064],
        [0.6301, 0.1582, 0.2536, 0.9868]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [10]:
#Lets make some random but reproducible tensors
rand_seed = 42
torch.manual_seed(rand_seed)
randC = torch.rand(3,4)
torch.manual_seed(rand_seed)
randD = torch.rand(3,4)
print(randC)
print(randD)
print(randC == randD)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
